travis:
  secure:
    BINSTAR_TOKEN: QIHKoqs0gh8UxkHUBRMRYrQo33POVYLc5sbH/GZVzjSFKZJVuxUEz4Sb0UKNBUKuk3DSHO975TOCmrg0j6K3DF94uF/dIUZ5LTaBZD6C0Z3fgyimX6ofVBD91cWauW/jUDHHHIA7rQLjg6KGIHpEgY9uZSmjea9vbaF0S6IAEnM7D7dZngTREizYpdZOPN1FCIW39Tl6y0geXIGHWT6yOC2IIq/GMjrrzGRocVWJ7CfAQm+/KVF8zTaPAGy3bftbjmh1xOyLEbOzWGUImsohIvwskna7fCvz+18CfUrtYk53HrS+D1+WJ6R746j4s16CA1OyzGEEzD8/TUniMYp06W+R8KdVeRTSlSdygrCKHFkKp/ek16GFd30iNmnFS5lybfBQsv/2XAuf42/ApCz3TOBH+GRDgZvk4vxEqpCHDN3rnXGCQ2ZUOrVj3BUg9eFcGGkk2vNLEZ0lGslzli/Li8b6Qi4036jJU4Vg4PGBIIoLDZtY+tYdMi4Mr53N3p59MRY2dhQqVoidYH0X9i3hd1sQ4QXJps7+KxvhtkR4zK2t0axn2neVnNg5j2nVoOw6Sx7kFRn6qIk3ZJXB4P2C17g5yJ4ssjZjJABNTWlQq9RtwYZLWoYiy3qkg8GhzDyjUSDVs3CwENSfC3/mA+5C1HNdBDFYpl++VHrYUwoK2WQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
