travis:
  secure:
    BINSTAR_TOKEN: QibvI05d8VOrxoC9Cx+tqny/j40KsPT/looExjOjDyKzBZtLiLYAdA8ZKAjs8pdsxpEpfUDl+fxinXSjZFjHcwiol0bew33p2nNDhCUmqHUReaUVJN1mCDTi8okqQA4s3hGjSFLtsTF1B2uivyc1aMI8up8o7VpQAyvaYQMrS8jT9YLlFltvbY6F6eDmFfLYuatV7WCsm0LlZNEOYT43qxv7Pz8GKKpA24tpKLYcTckWkuG31WmZu/yMzZSBDFtQMbx1Ps2D25ZN4hxTwNBzmWSrIJi93qO/8whbCzW74XkndOZwP4l8xeN4NsFE2PbEUsoFZR9gevR6DLnyY0fFKH8mnD1AH7b3mAgw77l0l+dBIdGmbbhTRLOJEmReTkdctjda09+U1gMvaS0fSjxTnazpZi/Lp5tDlkyeGE53RLQ5ioN5ClNAyOsR8a3WbMirAWa/82C88iJAG6JqokyOeo6HeCVl87kevNgL4CRoQ8W2u3sO5b90D0OmiT6lr1BJ6XJ5XEN9aodzXDAtNgQdt27Tq83VhX9ePFaIkx30ZetOcr4+qStdnTcVkXWcy8kiygfd5HJ6pssXZu9OvFi/9LLsHVAHDS323hWiHHwxZEDfv9jkWwkXOOXJ6oQF7b97pNt0cV/nA6zK+gj8+1Ab4cwKTnOTEReU1g2XzsuUaag=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
